TOP = ..

USER_LIBS = -nodefaultlibs -lc -lgcc

EXTRAINCDIRS = ./u8glib/src

TARGET = dmxrx

SRC = main.c \
      u8glib/src/u8g_com_io.c \
      u8glib/src/u8g_dev_st7565_nhd_c12864.c \
      u8glib/src/u8g_ll_api.c \
      u8glib/src/u8g_clip.c \
      u8glib/src/u8g_delay.c \
      u8glib/src/u8g_com_api.c \
      u8glib/src/u8g_pb16v1.c \
      u8glib/src/u8g_pb8v1.c \
      u8glib/src/u8g_pb.c \
      u8glib/src/u8g_com_atmega_sw_spi.c \
      u8glib/src/u8g_com_atmega_hw_spi.c \
      u8glib/src/u8g_state.c \
      u8glib/src/u8g_page.c \
      u8glib/src/u8g_font.c \
      u8glib/src/u8g_font_data.c \

include $(TOP)/mk/common.mk
